# Generated by Django 3.0 on 2019-12-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0002_auto_20191216_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursteps',
            name='string_date',
            field=models.CharField(default=99, max_length=10, verbose_name='string_date'),
            preserve_default=False,
        ),
    ]
